version: '3'
services:
  db:
    image: postgres
    container_name: odinbook-postgres-16
    volumes:
      - postgres_data:/var/lib/postgresql/data

    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=odinbook_production
      - POSTGRES_USER=odinbook
      - POSTGRES_PASSWORD=postgresdbforodinbookapp

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  redis:
    image: redis:6.0.10
    volumes:
      - redis_data:/data

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  odinbook-web:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  postgres_data: {}
  app-storage: {}
  elasticsearch_data: {}
  redis_data: {}
